# Taken from
# https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker

FROM python:3.9

WORKDIR /code

COPY requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY /src /code/src
COPY main.py main.py
COPY __init__.py __init__.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
