version: "3.9"  # optional since v1.27.0
services:
  web:
    # For running tests
    #entrypoint: "python"
    #command: "-m pytest tests -vv"
    build:
      context: ..
      dockerfile: docker/dockerfile
    ports:
      - "80:80"
    links:
      - postgres-markr
    environment:
      POSTGRES_HOST: "postgres-markr"
    depends_on:
      - postgres-markr
  postgres-markr:
    image: postgres:14
    volumes:
      - ${PWD}/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "stile"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"